# Generated by Django 3.0.6 on 2020-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='last_name',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
