# Generated by Django 3.0.6 on 2020-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0003_auto_20200607_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
