# Generated by Django 3.0.6 on 2020-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0004_auto_20200609_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='otp',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
