# Generated by Django 3.0.6 on 2020-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0006_auto_20200610_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
