# Generated by Django 3.0.6 on 2020-06-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0007_auto_20200610_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='tempuser',
            name='phone_number_verified',
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_signup.TempUser', to_field='phone_number')),
            ],
        ),
    ]
