# Generated by Django 3.0.6 on 2020-06-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0008_auto_20200611_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
