# Generated by Django 3.0.6 on 2020-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0011_auto_20200622_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
