# Generated by Django 3.0.6 on 2020-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0012_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
