# Generated by Django 3.0.6 on 2020-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='model_no',
            field=models.CharField(default='no model found', max_length=20),
        ),
    ]
